name: Code Pipeline Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::574736080095:role/GithubActions-CodeBuildRole
          aws-region: ap-southeast-2

      - name: AWS CodePipeline Trigger
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: ap-southeast-2
          pipeline-name: BuildContainerPipeline
